
// This file is generated by Gemini. DO NOT EDIT.
'use server';
/**
 * @fileOverview Generates a fake news article given a topic, category, and tone.
 *
 * - generateFakeNewsArticle - A function that handles the fake news article generation.
 * - GenerateFakeNewsArticleInput - The input type for the generateFakeNewsArticle function.
 * - GenerateFakeNewsArticleOutput - The return type for the generateFakeNewsArticle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFakeNewsArticleInputSchema = z.object({
  topic: z.string().describe('The topic of the fake news article.'),
  category: z.string().describe('The category of the fake news article.'),
  tone: z.string().describe('The tone of the fake news article.'),
});
export type GenerateFakeNewsArticleInput = z.infer<typeof GenerateFakeNewsArticleInputSchema>;

const GenerateFakeNewsArticleOutputSchema = z.object({
  title: z.string().describe('The catchy, AI-generated headline for the fake news article.'),
  article: z.string().describe('The body content of the generated fake news article.'),
});
export type GenerateFakeNewsArticleOutput = z.infer<typeof GenerateFakeNewsArticleOutputSchema>;

export async function generateFakeNewsArticle(
  input: GenerateFakeNewsArticleInput
): Promise<GenerateFakeNewsArticleOutput> {
  try {
    return await generateFakeNewsArticleFlow(input);
  } catch (error: any) {
    console.error("[TruthLensAI] Error in generateFakeNewsArticle flow execution:", error);
    if (error instanceof Error) {
        const flowErrorMessage = error.message || '';
        // Check for known, specific error messages from the inner flow
        if (flowErrorMessage.startsWith("The AI could not generate") || 
            flowErrorMessage.startsWith("AI model did not return") ||
            flowErrorMessage.startsWith("Article generation error:") ||
            flowErrorMessage.startsWith("Article generation failed:") ||
            flowErrorMessage.startsWith("An unexpected issue occurred during AI article processing") 
            ) {
            throw new Error(flowErrorMessage); 
        }
        // For other errors that made it this far, provide a slightly more specific generic message
        throw new Error(`Failed to generate article: An unexpected server issue occurred. (Details: ${flowErrorMessage.substring(0,150)})`);
    }
    // Fallback if not an Error instance (should be rare due to inner catch logic)
    throw new Error('Failed to generate article due to an unexpected server-side problem. Please check logs.');
  }
}

const prompt = ai.definePrompt({
  name: 'generateFakeNewsArticlePrompt',
  input: {schema: GenerateFakeNewsArticleInputSchema},
  output: {schema: GenerateFakeNewsArticleOutputSchema},
  prompt: `You are a professional fake news article writer.

You will be provided with a topic, category, and tone.

You MUST generate a catchy and relevant headline (title) for the article.
You will write a fake news article based on the topic, category, and tone.

Topic: {{{topic}}}
Category: {{{category}}}
Tone: {{{tone}}}

Headline: 
Article: `,
   // Basic safety settings - adjust as needed
  config: {
    safetySettings: [
      { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_MEDIUM_AND_ABOVE' },
      { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_MEDIUM_AND_ABOVE' },
      { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_MEDIUM_AND_ABOVE' },
      { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_MEDIUM_AND_ABOVE' },
    ],
  },
});

const generateFakeNewsArticleFlow = ai.defineFlow(
  {
    name: 'generateFakeNewsArticleFlow',
    inputSchema: GenerateFakeNewsArticleInputSchema,
    outputSchema: GenerateFakeNewsArticleOutputSchema,
  },
  async input => {
    try {
      const {output, candidates} = await prompt(input);
      if (!output || !output.article || !output.title) {
        if (candidates && candidates.length > 0) {
            const firstCandidate = candidates[0];
            if (firstCandidate.finishReason === 'SAFETY') {
                console.warn('[TruthLensAI] Article generation blocked by safety filters for input:', input, 'Finish message:', firstCandidate.finishMessage);
                throw new Error("The AI could not generate an article for this topic due to safety content policies. Please try a different topic.");
            }
            if (firstCandidate.finishReason === 'RECITATION') {
                 console.warn('[TruthLensAI] Article generation blocked due to recitation policy for input:', input, 'Finish message:', firstCandidate.finishMessage);
                throw new Error("The AI could not generate an article as it might resemble copyrighted material. Please try a different topic.");
            }
        }
        console.error('[TruthLensAI] Article generation failed: AI did not return a valid article structure (title and/or body missing) for input:', input);
        throw new Error('AI model did not return a complete article (title or body). Please try modifying your input or try again later.');
      }
      return output;
    } catch (error: any) {
        console.error("[TruthLensAI] Error during article generation prompt execution in flow:", error);
        if (error instanceof Error) {
          // Re-throw known user-friendly errors directly
          if (error.message.startsWith("The AI could not generate") || 
              error.message.startsWith("AI model did not return")) {
            throw error; 
          }
          // For other Error instances, create a new simplified error.
          // This helps ensure the message is clean for serialization and doesn't expose too much.
          throw new Error(`Article generation error: ${error.message.substring(0, 200)}`); 
        } else if (typeof error === 'string') {
          // If the error is just a string
          throw new Error(`Article generation failed: ${error.substring(0,200)}`);
        } else {
          // Fallback for truly unknown error structures from the prompt/Genkit layer
          throw new Error("An unexpected issue occurred during AI article processing. Please check server logs for details.");
        }
    }
  }
);
