// This file is generated by Gemini. DO NOT EDIT.
'use server';
/**
 * @fileOverview Generates a fake news article given a topic, category, and tone.
 *
 * - generateFakeNewsArticle - A function that handles the fake news article generation.
 * - GenerateFakeNewsArticleInput - The input type for the generateFakeNewsArticle function.
 * - GenerateFakeNewsArticleOutput - The return type for the generateFakeNewsArticle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFakeNewsArticleInputSchema = z.object({
  topic: z.string().describe('The topic of the fake news article.'),
  category: z.string().describe('The category of the fake news article.'),
  tone: z.string().describe('The tone of the fake news article.'),
});
export type GenerateFakeNewsArticleInput = z.infer<typeof GenerateFakeNewsArticleInputSchema>;

const GenerateFakeNewsArticleOutputSchema = z.object({
  article: z.string().describe('The generated fake news article.'),
});
export type GenerateFakeNewsArticleOutput = z.infer<typeof GenerateFakeNewsArticleOutputSchema>;

export async function generateFakeNewsArticle(
  input: GenerateFakeNewsArticleInput
): Promise<GenerateFakeNewsArticleOutput> {
  return generateFakeNewsArticleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateFakeNewsArticlePrompt',
  input: {schema: GenerateFakeNewsArticleInputSchema},
  output: {schema: GenerateFakeNewsArticleOutputSchema},
  prompt: `You are a professional fake news article writer.

You will be provided with a topic, category, and tone.

You will write a fake news article based on the topic, category, and tone.

Topic: {{{topic}}}
Category: {{{category}}}
Tone: {{{tone}}}

Article: `,
});

const generateFakeNewsArticleFlow = ai.defineFlow(
  {
    name: 'generateFakeNewsArticleFlow',
    inputSchema: GenerateFakeNewsArticleInputSchema,
    outputSchema: GenerateFakeNewsArticleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
